### ISSUE TITLE
Hurtigtast for instabart spiser hurtigtast for developer console på Mac

### ISSUE THREAD

**Issue by melwil** [appKom/notifier#28]
⌥⌘i er i dag hurtigtast for instabart, men dette er en shortcut som brukes i Chrome.

Ønske om at den enten endres eller at jeg kan slå av hurtigtaster.

**Comment by michaeljohansen** [comment]
You can change these hotkeys in the lower right corner of chrome://extensions - However, now that this hotkey crashes with a developer feature I think we should reassign the key or remove it (if not used a lot).

**Comment by melwil** [comment]
Uhm, my bad. Jeg har tenkt feil, lurte litt på hvorfor dette ikke hadde vært et issue tidligere.

Det er "Shift ⌘ i" som er instabart. Gått en smule varmt på jobben i dag :D

De kræsjer altså ikke.

**Comment by michaeljohansen** [comment]
I enjoy self-solving problems ^.^
