### ISSUE TITLE
Getting Online coffee notifications when not supposed to

### ISSUE THREAD

**Issue by draperunner** [appKom/notifier#30]
With affiliation set to Abakus and coffee notifications turned off in settings, I still get coffee notifications from Online's office.

Looks like the coffee statistics are correct though. They are from Abakus.

**Comment by michaeljohansen** [comment]
Thanks for the report. I'll have a look in the client and get back to you.

**Comment by michaeljohansen** [comment]
Notifier fetches nicely from Notiwire, which is located at https://passoa.online.ntnu.no/api/affiliation/abakus
@duvholt Any ideas about this one?

**Comment by duvholt** [comment]
No, it shouldn't. I think it sends websockets notifications, but Notifier shouldn't listen on those yet, right?

**Comment by michaeljohansen** [comment]
I'm not able to test the coffee buttons (obviously). Is the info provided for Abakus correct? Notifier only uses simple REST calls to Notiwire for now, no use of websockets yet.

**Comment by draperunner** [comment]
I can confirm that I just got a notification from Online although I am having Abakus as affiliation, with coffee notification subscription turned on.

**Comment by michaeljohansen** [comment]
Just a clarification: Did the notification say that coffee is available at the Online office, where it was supposed to say Abakus office? Or are you literally getting notifications when the button in Online's office is pressed? I'm not in Trondheim so I can't confirm whether this data is wrong or not:
https://passoa.online.ntnu.no/api/affiliation/online
https://passoa.online.ntnu.no/api/affiliation/abakus

**Comment by draperunner** [comment]
I am getting a notification when the button in Online's office is pressed, and it is with Online's logo and all. It fits correctly with the data from Online (your first link).

**Comment by michaeljohansen** [comment]
This is very odd. Are you sure you've set Abakus as your primary affiliation in Notifier? As in, the left one? Also, if so, can you please dump your localStorage and send it to me? Just inspect the Notifier popup and type `copy(localStorage)` in the console, then paste it in an email to me: michael@informatikk.org

**Comment by draperunner** [comment]
Just got a correct Abakus coffee update! It might have been an update bug, though I didn't perform a fresh install.

**Comment by michaeljohansen** [comment]
Good. I haven't had any success with replicating the problem. Most likely an update bug. Please reopen the issue if the problem resurfaces.
