### ISSUE TITLE
"Frakoblet fra Notiwire" when there are no meetings for that day

### ISSUE THREAD

**Issue by duvholt** [appKom/notifier#31]
Seems like notifier displays an error message when there are no meetings for that day. 

Output from API:
```json
{
	"meeting": {
		"message": "Ledig resten av dagen",
		"free": true,
		"meetings": []
	}
}
```

**Comment by michaeljohansen** [comment]
Thanks! Fixed.

:shipit: Notifier 5.1.3 and Notiwall 1.1.1 has been published for Chrome. 

⭕️ Won't bother publishing new patch version of Notifier for Opera as there's only a single user on Opera with Notifier installed. Btw, let me know if you guys want to look into the analytics.

Notifier users: 747
Notiwalls online: 5

The numbers are good. But note that there are very few fresh installs of Notifier this past year. I guess the marketing dept. hasn't been working too hard? ;P I usually sent out a yearly reminder about the existence of Notifier to all the “linjeforeninger” at Gløshaugen. People were usually very positive and surprised every time. Just a tip. :)
